CREATE SCHEMA IF NOT EXISTS demo;
USE chess;

DROP TABLE IF EXISTS demo;

CREATE TABLE `demo` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GREETING` varchar(128) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;

SELECT * from demo;