CREATE SCHEMA IF NOT EXISTS chess;
USE chess;

DROP TABLE IF EXISTS demo;

CREATE TABLE `demo` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GREETING` varchar(128) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
)

SELECT * from demo;
