CREATE SCHEMA IF NOT EXISTS chess;
USE chess;

DROP TABLE IF EXISTS DEMO;

CREATE TABLE `DEMO` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GREETING` varchar(128) DEFAULT NULL,
  `TIMESTAMP` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

SELECT * from DEMO;
